# Generated by Django 4.2.5 on 2023-11-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
                ('max_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('min_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('min_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hint', models.CharField(max_length=200)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.category')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
